# Site settings
title: Runequest
email: Flaze555@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Runequest is a visual novel made in Renpy.
  The game is a slice of puzzle and manipulation.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: SaradominBrew
github_username:  ChocolateMilk555

# Build settings
markdown: Chocolatemilk

theme: jekyll-theme-slate
